# Generated by Django 3.0.5 on 2021-06-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default='hcntqubzfh', max_length=10, null=True, verbose_name='Код подтверждения'),
        ),
    ]
