# Generated by Django 3.0.5 on 2021-06-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210619_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default='tkekgkkatu', max_length=10, null=True, verbose_name='Код подтверждения'),
        ),
    ]
