# Generated by Django 3.0.5 on 2021-06-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210619_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default='hzyrjnuvxx', max_length=10, null=True, verbose_name='Код подтверждения'),
        ),
    ]
