# Generated by Django 3.0.5 on 2021-06-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210618_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default='dyoezwkjrt', max_length=10, null=True, verbose_name='Код подтверждения'),
        ),
    ]
