# Generated by Django 3.0.5 on 2021-06-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210619_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default='krpaohefkc', max_length=10, null=True, verbose_name='Код подтверждения'),
        ),
    ]
