# Generated by Django 3.0.5 on 2021-06-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210618_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default='foabvdrdrx', max_length=10, null=True, verbose_name='Код подтверждения'),
        ),
    ]
