# Generated by Django 3.0.5 on 2021-09-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
    ]
