# Generated by Django 3.0.5 on 2021-06-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210615_1742'),
        ('users', '0004_auto_20210615_2015'),
    ]

    operations = [
    ]
