# Generated by Django 3.0.5 on 2021-06-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20210616_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default='nmtfxhsdey', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
