# Generated by Django 3.0.5 on 2021-06-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210620_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default='htzaffhuxa', max_length=10, null=True, verbose_name='Код подтверждения'),
        ),
    ]
