# Generated by Django 3.0.5 on 2021-06-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210616_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default='zunzxpsquy', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
