# Generated by Django 3.0.5 on 2021-06-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210616_1720'),
        ('users', '0009_auto_20210616_1300'),
    ]

    operations = [
    ]
