# Generated by Django 3.0.5 on 2021-06-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210616_1300'),
        ('users', '0007_merge_20210616_1622'),
    ]

    operations = [
    ]
