# Generated by Django 3.0.5 on 2021-06-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20210616_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default='calozjxznl', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
