# Generated by Django 3.0.5 on 2021-06-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210616_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default='barhdihava', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
