# Generated by Django 3.0.5 on 2021-06-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210616_1720'),
        ('users', '0017_auto_20210616_1955'),
    ]

    operations = [
    ]
