# Generated by Django 3.0.5 on 2021-06-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210617_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default='0123456789', max_length=10, null=True, verbose_name='Код подтверждения'),
        ),
    ]
