# Generated by Django 3.0.5 on 2021-06-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210616_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default='jjuvvurgla', max_length=10, null=True, verbose_name='Код подтверждения'),
        ),
    ]
