# Generated by Django 3.0.5 on 2021-06-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210617_1154'),
        ('users', '0036_auto_20210616_2222'),
    ]

    operations = [
    ]
