# Generated by Django 3.0.5 on 2021-06-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20210617_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default='vsasnalecp', max_length=10, null=True, verbose_name='Код подтверждения'),
        ),
    ]
