# Generated by Django 3.0.5 on 2021-06-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter the category name', max_length=200, verbose_name='category name')),
                ('slug', models.SlugField(help_text='enter the category reference label', unique=True, verbose_name='category reference label')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter the genre name', max_length=200, verbose_name='genre name')),
                ('slug', models.SlugField(help_text='enter the genre reference label', unique=True, verbose_name='genre reference label')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter the title name', max_length=200, verbose_name='title name')),
                ('year', models.IntegerField(help_text='enter the title year published', verbose_name='title year published')),
                ('rating', models.FloatField()),
                ('description', models.TextField(help_text='enter information about the title', verbose_name='title description')),
                ('category', models.ForeignKey(blank=True, help_text='select a category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='api.Category', verbose_name='category')),
                ('genre', models.ForeignKey(blank=True, help_text='select a genre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='api.Genre', verbose_name='genre')),
            ],
            options={
                'verbose_name': 'titles',
                'ordering': ('-rating',),
            },
        ),
    ]
