# Generated by Django 3.0.5 on 2021-06-20 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210619_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(help_text='add a comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Review', verbose_name='review'),
        ),
    ]
