# Generated by Django 3.0.5 on 2021-06-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210618_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, help_text='enter information about the title', null=True, verbose_name='title description'),
        ),
    ]
