# Generated by Django 3.0.5 on 2021-06-16 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_category_genre_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='enter your review here', verbose_name='review text')),
                ('score', models.FloatField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('title', models.ForeignKey(blank=True, help_text='add a title item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.Title', verbose_name='title')),
            ],
            options={
                'verbose_name': 'titles',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='enter your comment here', verbose_name='comment text')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('review', models.ForeignKey(blank=True, help_text='add a comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Review', verbose_name='review')),
            ],
            options={
                'verbose_name': 'comments',
                'ordering': ('-pub_date',),
            },
        ),
    ]
