# Generated by Django 3.0.5 on 2021-06-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210618_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(blank=True, help_text='enter the title year published', null=True, verbose_name='title year published'),
        ),
    ]
