# Generated by Django 3.0.5 on 2021-06-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
