# Generated by Django 3.0.5 on 2021-06-18 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210618_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-pk',), 'verbose_name': 'titles'},
        ),
    ]
