# Generated by Django 3.0.5 on 2021-06-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210620_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(help_text='enter your review score', verbose_name='review score'),
        ),
    ]
