# Generated by Django 3.0.5 on 2021-06-18 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210618_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pub_date',), 'verbose_name': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-pub_date',), 'verbose_name': 'titles'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-pk',), 'verbose_name': 'titles'},
        ),
    ]
