# Generated by Django 3.0.5 on 2021-06-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210616_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='select a genre', related_name='titles', to='api.Genre', verbose_name='genre'),
        ),
    ]
