# Generated by Django 3.0.5 on 2021-06-16 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_title_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'titles'},
        ),
    ]
