# Generated by Django 3.0.5 on 2021-06-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210616_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='title rating'),
        ),
    ]
