# Generated by Django 3.0.5 on 2021-06-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(help_text='enter your review score', verbose_name='review score'),
        ),
    ]
